# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 08:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userlogin', '0004_bloglike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloglike',
            name='like_count',
        ),
        migrations.AddField(
            model_name='bloglike',
            name='like_done',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_done', to=settings.AUTH_USER_MODEL),
        ),
    ]
