# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0005_auto_20160721_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglike',
            name='like_blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_blog', to='userlogin.Blog'),
        ),
    ]
