# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0006_auto_20160721_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloglike',
            name='time_liked',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
